version: '2.3'
services:
    jupyter:
        build:
            context: .
        image: dockerjupyter
        volumes:
            - ./:/home/jovyan/work
        ports:
            - 8888:8888
            
